spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/associations
    username: miguel
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database: associations
    database-platform: org.hibernate.dialect.MySqlDialect
