services:

  customers:
    image: mongo
    container_name: customers_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=miguel
      - MONGO_INITDB_ROOT_PASSWORD=1234

  associations:
    image: mysql
    container_name: associations_db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=associations
      - MYSQL_USER=miguel
      - MYSQL_PASSWORD=1234
    ports:
      - "33061:3306"

  raffles:
    image: mysql
    container_name: raffles_db
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=raffles
      - MYSQL_USER=miguel
      - MYSQL_PASSWORD=1234
    ports:
      - "33062:3306"

volumes:
  mongo:





