services:

  mongodb-container:
    image: mongo
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=miguel
      - MONGO_INITDB_ROOT_PASSWORD=1234
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=miguel
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_MONGODB_SERVER=mongodb

  mysql-container:
    image: mysql
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=docker-app
      - MYSQL_USER=miguel
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
